/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteByOrgApiKeysById200Response {
    #[serde(rename = "success")]
    pub success: Success,
}

impl DeleteByOrgApiKeysById200Response {
    pub fn new(success: Success) -> DeleteByOrgApiKeysById200Response {
        DeleteByOrgApiKeysById200Response {
            success,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Success {
    #[serde(rename = "true")]
    True,
}

impl Default for Success {
    fn default() -> Success {
        Self::True
    }
}

