/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetByOrgByRepoSync200ResponseStatusOneOf1 : A sync is currently in progress.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoSync200ResponseStatusOneOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl GetByOrgByRepoSync200ResponseStatusOneOf1 {
    /// A sync is currently in progress.
    pub fn new(r#type: Type) -> GetByOrgByRepoSync200ResponseStatusOneOf1 {
        GetByOrgByRepoSync200ResponseStatusOneOf1 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "syncing")]
    Syncing,
}

impl Default for Type {
    fn default() -> Type {
        Self::Syncing
    }
}

