/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetByOrgByRepoSync200ResponseStatusOneOf2 : The last sync failed with an error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoSync200ResponseStatusOneOf2 {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Error message from the last failed sync attempt
    #[serde(rename = "message")]
    pub message: String,
}

impl GetByOrgByRepoSync200ResponseStatusOneOf2 {
    /// The last sync failed with an error.
    pub fn new(r#type: Type, message: String) -> GetByOrgByRepoSync200ResponseStatusOneOf2 {
        GetByOrgByRepoSync200ResponseStatusOneOf2 {
            r#type,
            message,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "error")]
    Error,
}

impl Default for Type {
    fn default() -> Type {
        Self::Error
    }
}

