/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrg200Response {
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<String>,
    #[serde(rename = "num_repos")]
    pub num_repos: i64,
}

impl GetByOrg200Response {
    pub fn new(created_at: Option<String>, num_repos: i64) -> GetByOrg200Response {
        GetByOrg200Response {
            created_at,
            num_repos,
        }
    }
}

