/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoCommitsBySha200Response {
    #[serde(rename = "sha")]
    pub sha: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "author")]
    pub author: models::GetByOrgByRepoCommits200ResponseCommitsInnerCommitter,
    #[serde(rename = "committer")]
    pub committer: models::GetByOrgByRepoCommits200ResponseCommitsInnerCommitter,
}

impl GetByOrgByRepoCommitsBySha200Response {
    pub fn new(sha: String, message: String, author: models::GetByOrgByRepoCommits200ResponseCommitsInnerCommitter, committer: models::GetByOrgByRepoCommits200ResponseCommitsInnerCommitter) -> GetByOrgByRepoCommitsBySha200Response {
        GetByOrgByRepoCommitsBySha200Response {
            sha,
            message,
            author,
            committer,
        }
    }
}

