/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoCommits200Response {
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "commits")]
    pub commits: Vec<models::GetByOrgByRepoCommits200ResponseCommitsInner>,
}

impl GetByOrgByRepoCommits200Response {
    pub fn new(next_cursor: Option<String>, has_more: bool, commits: Vec<models::GetByOrgByRepoCommits200ResponseCommitsInner>) -> GetByOrgByRepoCommits200Response {
        GetByOrgByRepoCommits200Response {
            next_cursor,
            has_more,
            commits,
        }
    }
}

