/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgApiKeys200Response {
    #[serde(rename = "api_keys")]
    pub api_keys: Vec<models::GetByOrgApiKeys200ResponseApiKeysInner>,
}

impl GetByOrgApiKeys200Response {
    pub fn new(api_keys: Vec<models::GetByOrgApiKeys200ResponseApiKeysInner>) -> GetByOrgApiKeys200Response {
        GetByOrgApiKeys200Response {
            api_keys,
        }
    }
}

