/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoDiff200ResponseStats {
    #[serde(rename = "files")]
    pub files: f64,
    #[serde(rename = "additions")]
    pub additions: f64,
    #[serde(rename = "deletions")]
    pub deletions: f64,
    #[serde(rename = "changes")]
    pub changes: f64,
}

impl GetByOrgByRepoDiff200ResponseStats {
    pub fn new(files: f64, additions: f64, deletions: f64, changes: f64) -> GetByOrgByRepoDiff200ResponseStats {
        GetByOrgByRepoDiff200ResponseStats {
            files,
            additions,
            deletions,
            changes,
        }
    }
}

