/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoContent200ResponseAnyOf2EntriesInnerAnyOf2 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "path", deserialize_with = "Option::deserialize")]
    pub path: Option<String>,
    #[serde(rename = "sha", deserialize_with = "Option::deserialize")]
    pub sha: Option<String>,
}

impl GetByOrgByRepoContent200ResponseAnyOf2EntriesInnerAnyOf2 {
    pub fn new(r#type: Type, name: Option<String>, path: Option<String>, sha: Option<String>) -> GetByOrgByRepoContent200ResponseAnyOf2EntriesInnerAnyOf2 {
        GetByOrgByRepoContent200ResponseAnyOf2EntriesInnerAnyOf2 {
            r#type,
            name,
            path,
            sha,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "dir")]
    Dir,
}

impl Default for Type {
    fn default() -> Type {
        Self::Dir
    }
}

