/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoContent200ResponseAnyOf2EntriesInner {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "sha")]
    pub sha: String,
    #[serde(rename = "size")]
    pub size: f64,
    #[serde(rename = "executable")]
    pub executable: bool,
    #[serde(rename = "last_commit_at")]
    pub last_commit_at: String,
}

impl GetByOrgByRepoContent200ResponseAnyOf2EntriesInner {
    pub fn new(r#type: Type, name: String, path: String, sha: String, size: f64, executable: bool, last_commit_at: String) -> GetByOrgByRepoContent200ResponseAnyOf2EntriesInner {
        GetByOrgByRepoContent200ResponseAnyOf2EntriesInner {
            r#type,
            name,
            path,
            sha,
            size,
            executable,
            last_commit_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "symlink")]
    Symlink,
    #[serde(rename = "dir")]
    Dir,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}

