/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoContent200Response {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "sha")]
    pub sha: String,
    #[serde(rename = "size")]
    pub size: f64,
    #[serde(rename = "encoding")]
    pub encoding: Encoding,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "executable")]
    pub executable: bool,
    #[serde(rename = "last_commit_at")]
    pub last_commit_at: String,
    #[serde(rename = "child_count")]
    pub child_count: i32,
    #[serde(rename = "entries")]
    pub entries: Vec<models::GetByOrgByRepoContent200ResponseAnyOf2EntriesInner>,
    #[serde(rename = "next_cursor")]
    pub next_cursor: String,
    #[serde(rename = "has_more")]
    pub has_more: bool,
}

impl GetByOrgByRepoContent200Response {
    pub fn new(r#type: Type, name: String, path: String, sha: String, size: f64, encoding: Encoding, content: String, executable: bool, last_commit_at: String, child_count: i32, entries: Vec<models::GetByOrgByRepoContent200ResponseAnyOf2EntriesInner>, next_cursor: String, has_more: bool) -> GetByOrgByRepoContent200Response {
        GetByOrgByRepoContent200Response {
            r#type,
            name,
            path,
            sha,
            size,
            encoding,
            content,
            executable,
            last_commit_at,
            child_count,
            entries,
            next_cursor,
            has_more,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "symlink")]
    Symlink,
    #[serde(rename = "dir")]
    Dir,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Encoding {
    #[serde(rename = "base64")]
    Base64,
}

impl Default for Encoding {
    fn default() -> Encoding {
        Self::Base64
    }
}

