/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgRepos200Response {
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "repos")]
    pub repos: Vec<models::GetByOrgRepos200ResponseReposInner>,
}

impl GetByOrgRepos200Response {
    pub fn new(next_cursor: Option<String>, has_more: bool, repos: Vec<models::GetByOrgRepos200ResponseReposInner>) -> GetByOrgRepos200Response {
        GetByOrgRepos200Response {
            next_cursor,
            has_more,
            repos,
        }
    }
}

