/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAnalytics200ResponseAnalyticsSummary {
    #[serde(rename = "totalLines")]
    pub total_lines: f64,
    #[serde(rename = "aiLines")]
    pub ai_lines: f64,
    #[serde(rename = "humanLines")]
    pub human_lines: f64,
    #[serde(rename = "providers")]
    pub providers: std::collections::HashMap<String, f64>,
    #[serde(rename = "models")]
    pub models: std::collections::HashMap<String, f64>,
    #[serde(rename = "updated", deserialize_with = "Option::deserialize")]
    pub updated: Option<String>,
}

impl GetByOrgByRepoAnalytics200ResponseAnalyticsSummary {
    pub fn new(total_lines: f64, ai_lines: f64, human_lines: f64, providers: std::collections::HashMap<String, f64>, models: std::collections::HashMap<String, f64>, updated: Option<String>) -> GetByOrgByRepoAnalytics200ResponseAnalyticsSummary {
        GetByOrgByRepoAnalytics200ResponseAnalyticsSummary {
            total_lines,
            ai_lines,
            human_lines,
            providers,
            models,
            updated,
        }
    }
}

