/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAnalytics200ResponseAnalyticsHistoryInner {
    #[serde(rename = "date", deserialize_with = "Option::deserialize")]
    pub date: Option<String>,
    #[serde(rename = "sha", deserialize_with = "Option::deserialize")]
    pub sha: Option<String>,
    #[serde(rename = "message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message: Option<Option<String>>,
    #[serde(rename = "author", deserialize_with = "Option::deserialize")]
    pub author: Option<String>,
    #[serde(rename = "added")]
    pub added: f64,
    #[serde(rename = "removed")]
    pub removed: f64,
    #[serde(rename = "aiLines")]
    pub ai_lines: f64,
    #[serde(rename = "providers", skip_serializing_if = "Option::is_none")]
    pub providers: Option<std::collections::HashMap<String, f64>>,
    #[serde(rename = "models", skip_serializing_if = "Option::is_none")]
    pub models: Option<std::collections::HashMap<String, f64>>,
}

impl GetByOrgByRepoAnalytics200ResponseAnalyticsHistoryInner {
    pub fn new(date: Option<String>, sha: Option<String>, author: Option<String>, added: f64, removed: f64, ai_lines: f64) -> GetByOrgByRepoAnalytics200ResponseAnalyticsHistoryInner {
        GetByOrgByRepoAnalytics200ResponseAnalyticsHistoryInner {
            date,
            sha,
            message: None,
            author,
            added,
            removed,
            ai_lines,
            providers: None,
            models: None,
        }
    }
}

