/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepo202Response {
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    #[serde(rename = "org", deserialize_with = "Option::deserialize")]
    pub org: Option<String>,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "default_branch", deserialize_with = "Option::deserialize")]
    pub default_branch: Option<String>,
    #[serde(rename = "head_sha", deserialize_with = "Option::deserialize")]
    pub head_sha: Option<String>,
    #[serde(rename = "size_bytes")]
    pub size_bytes: f64,
    #[serde(rename = "last_push_at", deserialize_with = "Option::deserialize")]
    pub last_push_at: Option<String>,
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<String>,
    #[serde(rename = "upstream", deserialize_with = "Option::deserialize")]
    pub upstream: Option<models::GetByOrgRepos200ResponseReposInnerUpstream>,
    #[serde(rename = "status")]
    pub status: Status,
}

impl GetByOrgByRepo202Response {
    pub fn new(id: Option<String>, org: Option<String>, name: Option<String>, default_branch: Option<String>, head_sha: Option<String>, size_bytes: f64, last_push_at: Option<String>, created_at: Option<String>, upstream: Option<models::GetByOrgRepos200ResponseReposInnerUpstream>, status: Status) -> GetByOrgByRepo202Response {
        GetByOrgByRepo202Response {
            id,
            org,
            name,
            default_branch,
            head_sha,
            size_bytes,
            last_push_at,
            created_at,
            upstream,
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "syncing")]
    Syncing,
}

impl Default for Status {
    fn default() -> Status {
        Self::Syncing
    }
}

