/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAnalytics200ResponseAnalytics {
    #[serde(rename = "version")]
    pub version: Version,
    #[serde(rename = "summary")]
    pub summary: models::GetByOrgByRepoAnalytics200ResponseAnalyticsSummary,
    #[serde(rename = "contributors")]
    pub contributors: std::collections::HashMap<String, models::GetByOrgByRepoAnalytics200ResponseAnalyticsContributorsValue>,
    #[serde(rename = "history")]
    pub history: Vec<models::GetByOrgByRepoAnalytics200ResponseAnalyticsHistoryInner>,
    #[serde(rename = "_meta", skip_serializing_if = "Option::is_none")]
    pub _meta: Option<models::GetByOrgByRepoAnalytics200ResponseAnalyticsMeta>,
}

impl GetByOrgByRepoAnalytics200ResponseAnalytics {
    pub fn new(version: Version, summary: models::GetByOrgByRepoAnalytics200ResponseAnalyticsSummary, contributors: std::collections::HashMap<String, models::GetByOrgByRepoAnalytics200ResponseAnalyticsContributorsValue>, history: Vec<models::GetByOrgByRepoAnalytics200ResponseAnalyticsHistoryInner>) -> GetByOrgByRepoAnalytics200ResponseAnalytics {
        GetByOrgByRepoAnalytics200ResponseAnalytics {
            version,
            summary,
            contributors,
            history,
            _meta: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Version {
    #[serde(rename = "2")]
    Variant2,
}

impl Default for Version {
    fn default() -> Version {
        Self::Variant2
    }
}

