/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgApiKeys400Response {
    #[serde(rename = "error")]
    pub error: models::GetByOrgApiKeys400ResponseError,
}

impl GetByOrgApiKeys400Response {
    pub fn new(error: models::GetByOrgApiKeys400ResponseError) -> GetByOrgApiKeys400Response {
        GetByOrgApiKeys400Response {
            error,
        }
    }
}

