/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoDiff200Response {
    #[serde(rename = "base", deserialize_with = "Option::deserialize")]
    pub base: Option<String>,
    #[serde(rename = "head", deserialize_with = "Option::deserialize")]
    pub head: Option<String>,
    #[serde(rename = "stats")]
    pub stats: models::GetByOrgByRepoDiff200ResponseStats,
    #[serde(rename = "files")]
    pub files: Vec<models::GetByOrgByRepoDiff200ResponseFilesInner>,
    #[serde(rename = "filtered_files")]
    pub filtered_files: Vec<models::GetByOrgByRepoDiff200ResponseFilteredFilesInner>,
}

impl GetByOrgByRepoDiff200Response {
    pub fn new(base: Option<String>, head: Option<String>, stats: models::GetByOrgByRepoDiff200ResponseStats, files: Vec<models::GetByOrgByRepoDiff200ResponseFilesInner>, filtered_files: Vec<models::GetByOrgByRepoDiff200ResponseFilteredFilesInner>) -> GetByOrgByRepoDiff200Response {
        GetByOrgByRepoDiff200Response {
            base,
            head,
            stats,
            files,
            filtered_files,
        }
    }
}

