/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAnalytics200ResponseAnalyticsMeta {
    #[serde(rename = "lastAttempt", deserialize_with = "Option::deserialize")]
    pub last_attempt: Option<String>,
    #[serde(rename = "lastSuccess", deserialize_with = "Option::deserialize")]
    pub last_success: Option<String>,
    #[serde(rename = "lastError", deserialize_with = "Option::deserialize")]
    pub last_error: Option<String>,
}

impl GetByOrgByRepoAnalytics200ResponseAnalyticsMeta {
    pub fn new(last_attempt: Option<String>, last_success: Option<String>, last_error: Option<String>) -> GetByOrgByRepoAnalytics200ResponseAnalyticsMeta {
        GetByOrgByRepoAnalytics200ResponseAnalyticsMeta {
            last_attempt,
            last_success,
            last_error,
        }
    }
}

