/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoSync200Response {
    #[serde(rename = "last_sync_attempt", deserialize_with = "Option::deserialize")]
    pub last_sync_attempt: Option<String>,
    #[serde(rename = "last_sync_success", deserialize_with = "Option::deserialize")]
    pub last_sync_success: Option<String>,
    #[serde(rename = "status")]
    pub status: models::GetByOrgByRepoSync200ResponseStatus,
}

impl GetByOrgByRepoSync200Response {
    pub fn new(last_sync_attempt: Option<String>, last_sync_success: Option<String>, status: models::GetByOrgByRepoSync200ResponseStatus) -> GetByOrgByRepoSync200Response {
        GetByOrgByRepoSync200Response {
            last_sync_attempt,
            last_sync_success,
            status,
        }
    }
}

