/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAnalytics200Response {
    #[serde(rename = "analytics", deserialize_with = "Option::deserialize")]
    pub analytics: Option<models::GetByOrgByRepoAnalytics200ResponseAnalytics>,
    #[serde(rename = "status")]
    pub status: Status,
}

impl GetByOrgByRepoAnalytics200Response {
    pub fn new(analytics: Option<models::GetByOrgByRepoAnalytics200ResponseAnalytics>, status: Status) -> GetByOrgByRepoAnalytics200Response {
        GetByOrgByRepoAnalytics200Response {
            analytics,
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "current")]
    Current,
    #[serde(rename = "stale")]
    Stale,
    #[serde(rename = "none")]
    None,
}

impl Default for Status {
    fn default() -> Status {
        Self::Current
    }
}

