/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoContent200ResponseAnyOf2 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "path", deserialize_with = "Option::deserialize")]
    pub path: Option<String>,
    #[serde(rename = "sha", deserialize_with = "Option::deserialize")]
    pub sha: Option<String>,
    #[serde(rename = "child_count")]
    pub child_count: i64,
    #[serde(rename = "entries")]
    pub entries: Vec<models::GetByOrgByRepoContent200ResponseAnyOf2EntriesInner>,
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
}

impl GetByOrgByRepoContent200ResponseAnyOf2 {
    pub fn new(r#type: Type, name: Option<String>, path: Option<String>, sha: Option<String>, child_count: i64, entries: Vec<models::GetByOrgByRepoContent200ResponseAnyOf2EntriesInner>, next_cursor: Option<String>, has_more: bool) -> GetByOrgByRepoContent200ResponseAnyOf2 {
        GetByOrgByRepoContent200ResponseAnyOf2 {
            r#type,
            name,
            path,
            sha,
            child_count,
            entries,
            next_cursor,
            has_more,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "dir")]
    Dir,
}

impl Default for Type {
    fn default() -> Type {
        Self::Dir
    }
}

