/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAgentblame200Response {
    #[serde(rename = "attributions")]
    pub attributions: std::collections::HashMap<String, Vec<models::GetByOrgByRepoAgentblame200ResponseAttributionsValueInner>>,
    #[serde(rename = "stats")]
    pub stats: models::GetByOrgByRepoAgentblame200ResponseStats,
}

impl GetByOrgByRepoAgentblame200Response {
    pub fn new(attributions: std::collections::HashMap<String, Vec<models::GetByOrgByRepoAgentblame200ResponseAttributionsValueInner>>, stats: models::GetByOrgByRepoAgentblame200ResponseStats) -> GetByOrgByRepoAgentblame200Response {
        GetByOrgByRepoAgentblame200Response {
            attributions,
            stats,
        }
    }
}

