/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoContent200ResponseAnyOf1 {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "path", deserialize_with = "Option::deserialize")]
    pub path: Option<String>,
    #[serde(rename = "sha", deserialize_with = "Option::deserialize")]
    pub sha: Option<String>,
    #[serde(rename = "size")]
    pub size: f64,
    #[serde(rename = "encoding")]
    pub encoding: Encoding,
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
    #[serde(rename = "mode")]
    pub mode: i64,
}

impl GetByOrgByRepoContent200ResponseAnyOf1 {
    pub fn new(r#type: Type, name: Option<String>, path: Option<String>, sha: Option<String>, size: f64, encoding: Encoding, content: Option<String>, mode: i64) -> GetByOrgByRepoContent200ResponseAnyOf1 {
        GetByOrgByRepoContent200ResponseAnyOf1 {
            r#type,
            name,
            path,
            sha,
            size,
            encoding,
            content,
            mode,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "symlink")]
    Symlink,
}

impl Default for Type {
    fn default() -> Type {
        Self::Symlink
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Encoding {
    #[serde(rename = "base64")]
    Base64,
}

impl Default for Encoding {
    fn default() -> Encoding {
        Self::Base64
    }
}

