/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAnalytics200ResponseAnalyticsContributorsValue {
    #[serde(rename = "totalLines")]
    pub total_lines: f64,
    #[serde(rename = "aiLines")]
    pub ai_lines: f64,
    #[serde(rename = "providers")]
    pub providers: std::collections::HashMap<String, f64>,
    #[serde(rename = "models")]
    pub models: std::collections::HashMap<String, f64>,
    #[serde(rename = "commitCount")]
    pub commit_count: f64,
}

impl GetByOrgByRepoAnalytics200ResponseAnalyticsContributorsValue {
    pub fn new(total_lines: f64, ai_lines: f64, providers: std::collections::HashMap<String, f64>, models: std::collections::HashMap<String, f64>, commit_count: f64) -> GetByOrgByRepoAnalytics200ResponseAnalyticsContributorsValue {
        GetByOrgByRepoAnalytics200ResponseAnalyticsContributorsValue {
            total_lines,
            ai_lines,
            providers,
            models,
            commit_count,
        }
    }
}

