/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgApiKeys200ResponseApiKeysInner {
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "last_used_at", deserialize_with = "Option::deserialize")]
    pub last_used_at: Option<String>,
    #[serde(rename = "expires_at", deserialize_with = "Option::deserialize")]
    pub expires_at: Option<String>,
    #[serde(rename = "revoked_at", deserialize_with = "Option::deserialize")]
    pub revoked_at: Option<String>,
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<String>,
}

impl GetByOrgApiKeys200ResponseApiKeysInner {
    pub fn new(id: Option<String>, name: Option<String>, scopes: Vec<String>, last_used_at: Option<String>, expires_at: Option<String>, revoked_at: Option<String>, created_at: Option<String>) -> GetByOrgApiKeys200ResponseApiKeysInner {
        GetByOrgApiKeys200ResponseApiKeysInner {
            id,
            name,
            scopes,
            last_used_at,
            expires_at,
            revoked_at,
            created_at,
        }
    }
}

