/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoBranches200ResponseBranchesInner {
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "head_sha", deserialize_with = "Option::deserialize")]
    pub head_sha: Option<String>,
    #[serde(rename = "is_default")]
    pub is_default: bool,
}

impl GetByOrgByRepoBranches200ResponseBranchesInner {
    pub fn new(name: Option<String>, head_sha: Option<String>, is_default: bool) -> GetByOrgByRepoBranches200ResponseBranchesInner {
        GetByOrgByRepoBranches200ResponseBranchesInner {
            name,
            head_sha,
            is_default,
        }
    }
}

