/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoWebhooks200Response {
    #[serde(rename = "webhooks")]
    pub webhooks: Vec<models::GetByOrgByRepoWebhooks200ResponseWebhooksInner>,
}

impl GetByOrgByRepoWebhooks200Response {
    pub fn new(webhooks: Vec<models::GetByOrgByRepoWebhooks200ResponseWebhooksInner>) -> GetByOrgByRepoWebhooks200Response {
        GetByOrgByRepoWebhooks200Response {
            webhooks,
        }
    }
}

