/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoCommits200ResponseCommitsInner {
    #[serde(rename = "sha", deserialize_with = "Option::deserialize")]
    pub sha: Option<String>,
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<String>,
    #[serde(rename = "author")]
    pub author: models::GetByOrgByRepoCommits200ResponseCommitsInnerAuthor,
    #[serde(rename = "committer")]
    pub committer: models::GetByOrgByRepoCommits200ResponseCommitsInnerCommitter,
}

impl GetByOrgByRepoCommits200ResponseCommitsInner {
    pub fn new(sha: Option<String>, message: Option<String>, author: models::GetByOrgByRepoCommits200ResponseCommitsInnerAuthor, committer: models::GetByOrgByRepoCommits200ResponseCommitsInnerCommitter) -> GetByOrgByRepoCommits200ResponseCommitsInner {
        GetByOrgByRepoCommits200ResponseCommitsInner {
            sha,
            message,
            author,
            committer,
        }
    }
}

