/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAgentblame200ResponseStats {
    #[serde(rename = "total_lines")]
    pub total_lines: f64,
    #[serde(rename = "ai_lines")]
    pub ai_lines: f64,
    #[serde(rename = "human_lines")]
    pub human_lines: f64,
    #[serde(rename = "ai_percentage")]
    pub ai_percentage: f64,
}

impl GetByOrgByRepoAgentblame200ResponseStats {
    pub fn new(total_lines: f64, ai_lines: f64, human_lines: f64, ai_percentage: f64) -> GetByOrgByRepoAgentblame200ResponseStats {
        GetByOrgByRepoAgentblame200ResponseStats {
            total_lines,
            ai_lines,
            human_lines,
            ai_percentage,
        }
    }
}

