/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetByOrgByRepoSync200ResponseStatus : What the status of the last sync was.
/// What the status of the last sync was.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetByOrgByRepoSync200ResponseStatus {
    GetByOrgByRepoSync200ResponseStatusOneOf(models::GetByOrgByRepoSync200ResponseStatusOneOf),
    GetByOrgByRepoSync200ResponseStatusOneOf1(models::GetByOrgByRepoSync200ResponseStatusOneOf1),
    GetByOrgByRepoSync200ResponseStatusOneOf2(models::GetByOrgByRepoSync200ResponseStatusOneOf2),
}

impl Default for GetByOrgByRepoSync200ResponseStatus {
    fn default() -> Self {
        Self::GetByOrgByRepoSync200ResponseStatusOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "syncing")]
    Syncing,
    #[serde(rename = "error")]
    Error,
}

impl Default for Type {
    fn default() -> Type {
        Self::Ok
    }
}

