/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgRepos200ResponseReposInner {
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    #[serde(rename = "org", deserialize_with = "Option::deserialize")]
    pub org: Option<String>,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "default_branch", deserialize_with = "Option::deserialize")]
    pub default_branch: Option<String>,
    #[serde(rename = "head_sha", deserialize_with = "Option::deserialize")]
    pub head_sha: Option<String>,
    #[serde(rename = "size_bytes")]
    pub size_bytes: f64,
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<String>,
    #[serde(rename = "upstream", deserialize_with = "Option::deserialize")]
    pub upstream: Option<models::GetByOrgRepos200ResponseReposInnerUpstream>,
}

impl GetByOrgRepos200ResponseReposInner {
    pub fn new(id: Option<String>, org: Option<String>, name: Option<String>, default_branch: Option<String>, head_sha: Option<String>, size_bytes: f64, created_at: Option<String>, upstream: Option<models::GetByOrgRepos200ResponseReposInnerUpstream>) -> GetByOrgRepos200ResponseReposInner {
        GetByOrgRepos200ResponseReposInner {
            id,
            org,
            name,
            default_branch,
            head_sha,
            size_bytes,
            created_at,
            upstream,
        }
    }
}

