/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgRepos200ResponseReposInnerUpstreamAutosync {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Polling period in seconds
    #[serde(rename = "period")]
    pub period: f64,
    /// Conflict resolution strategy. \"none\" means sync will fail on conflicts.
    #[serde(rename = "resolution_strategy")]
    pub resolution_strategy: ResolutionStrategy,
}

impl GetByOrgRepos200ResponseReposInnerUpstreamAutosync {
    pub fn new(r#type: Type, period: f64, resolution_strategy: ResolutionStrategy) -> GetByOrgRepos200ResponseReposInnerUpstreamAutosync {
        GetByOrgRepos200ResponseReposInnerUpstreamAutosync {
            r#type,
            period,
            resolution_strategy,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "poll")]
    Poll,
}

impl Default for Type {
    fn default() -> Type {
        Self::Poll
    }
}
/// Conflict resolution strategy. \"none\" means sync will fail on conflicts.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResolutionStrategy {
    #[serde(rename = "none")]
    None,
}

impl Default for ResolutionStrategy {
    fn default() -> ResolutionStrategy {
        Self::None
    }
}

