/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoBranches200Response {
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "branches")]
    pub branches: Vec<models::GetByOrgByRepoBranches200ResponseBranchesInner>,
}

impl GetByOrgByRepoBranches200Response {
    pub fn new(next_cursor: Option<String>, has_more: bool, branches: Vec<models::GetByOrgByRepoBranches200ResponseBranchesInner>) -> GetByOrgByRepoBranches200Response {
        GetByOrgByRepoBranches200Response {
            next_cursor,
            has_more,
            branches,
        }
    }
}

