/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoAgentblame200ResponseAttributionsValueInner {
    #[serde(rename = "lineNumber")]
    pub line_number: f64,
    #[serde(rename = "provider", deserialize_with = "Option::deserialize")]
    pub provider: Option<String>,
    #[serde(rename = "model", deserialize_with = "Option::deserialize")]
    pub model: Option<String>,
    #[serde(rename = "confidence")]
    pub confidence: f64,
    #[serde(rename = "match_type", deserialize_with = "Option::deserialize")]
    pub match_type: Option<String>,
}

impl GetByOrgByRepoAgentblame200ResponseAttributionsValueInner {
    pub fn new(line_number: f64, provider: Option<String>, model: Option<String>, confidence: f64, match_type: Option<String>) -> GetByOrgByRepoAgentblame200ResponseAttributionsValueInner {
        GetByOrgByRepoAgentblame200ResponseAttributionsValueInner {
            line_number,
            provider,
            model,
            confidence,
            match_type,
        }
    }
}

