/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoCommits200ResponseCommitsInnerCommitter {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
}

impl GetByOrgByRepoCommits200ResponseCommitsInnerCommitter {
    pub fn new(name: String, email: String) -> GetByOrgByRepoCommits200ResponseCommitsInnerCommitter {
        GetByOrgByRepoCommits200ResponseCommitsInnerCommitter {
            name,
            email,
            date: None,
        }
    }
}

