/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetByOrgByRepoDiff200ResponseFilteredFilesInner {
    #[serde(rename = "path", deserialize_with = "Option::deserialize")]
    pub path: Option<String>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "old_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub old_path: Option<Option<String>>,
    #[serde(rename = "bytes", skip_serializing_if = "Option::is_none")]
    pub bytes: Option<f64>,
    #[serde(rename = "is_eof", skip_serializing_if = "Option::is_none")]
    pub is_eof: Option<bool>,
}

impl GetByOrgByRepoDiff200ResponseFilteredFilesInner {
    pub fn new(path: Option<String>, status: Status) -> GetByOrgByRepoDiff200ResponseFilteredFilesInner {
        GetByOrgByRepoDiff200ResponseFilteredFilesInner {
            path,
            status,
            old_path: None,
            bytes: None,
            is_eof: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "A")]
    A,
    #[serde(rename = "M")]
    M,
    #[serde(rename = "D")]
    D,
    #[serde(rename = "R")]
    R,
    #[serde(rename = "C")]
    C,
    #[serde(rename = "T")]
    T,
}

impl Default for Status {
    fn default() -> Status {
        Self::A
    }
}

