/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchByOrgByRepoRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "upstream", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upstream: Option<Option<models::PatchByOrgByRepoRequestUpstream>>,
}

impl PatchByOrgByRepoRequest {
    pub fn new() -> PatchByOrgByRepoRequest {
        PatchByOrgByRepoRequest {
            name: None,
            upstream: None,
        }
    }
}

