/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgReposRequestUpstreamAutosyncOneOf {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// Polling period in seconds (60s to 24.8d)
    #[serde(rename = "period")]
    pub period: u32,
    /// Conflict resolution strategy. \"none\" means sync will fail on conflicts.
    #[serde(rename = "resolution_strategy", skip_serializing_if = "Option::is_none")]
    pub resolution_strategy: Option<ResolutionStrategy>,
}

impl PostByOrgReposRequestUpstreamAutosyncOneOf {
    pub fn new(r#type: Type, period: u32) -> PostByOrgReposRequestUpstreamAutosyncOneOf {
        PostByOrgReposRequestUpstreamAutosyncOneOf {
            r#type,
            period,
            resolution_strategy: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "poll")]
    Poll,
}

impl Default for Type {
    fn default() -> Type {
        Self::Poll
    }
}
/// Conflict resolution strategy. \"none\" means sync will fail on conflicts.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResolutionStrategy {
    #[serde(rename = "none")]
    None,
}

impl Default for ResolutionStrategy {
    fn default() -> ResolutionStrategy {
        Self::None
    }
}

