/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgRepos201Response {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "org")]
    pub org: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "default_branch")]
    pub default_branch: String,
    #[serde(rename = "head_sha", deserialize_with = "Option::deserialize")]
    pub head_sha: Option<String>,
    #[serde(rename = "size_bytes")]
    pub size_bytes: f64,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "upstream", deserialize_with = "Option::deserialize")]
    pub upstream: Option<models::GetByOrgRepos200ResponseReposInnerUpstream>,
}

impl PostByOrgRepos201Response {
    pub fn new(id: String, org: String, name: String, default_branch: String, head_sha: Option<String>, size_bytes: f64, created_at: String, upstream: Option<models::GetByOrgRepos200ResponseReposInnerUpstream>) -> PostByOrgRepos201Response {
        PostByOrgRepos201Response {
            id,
            org,
            name,
            default_branch,
            head_sha,
            size_bytes,
            created_at,
            upstream,
        }
    }
}

