/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoLfsObjectsRequestObjectsInner {
    #[serde(rename = "oid")]
    pub oid: String,
    #[serde(rename = "size")]
    pub size: u64,
}

impl PostByOrgByRepoLfsObjectsRequestObjectsInner {
    pub fn new(oid: String, size: u64) -> PostByOrgByRepoLfsObjectsRequestObjectsInner {
        PostByOrgByRepoLfsObjectsRequestObjectsInner {
            oid,
            size,
        }
    }
}

