/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostByOrgReposRequestUpstreamAutosync : Optionally enable automatic sync from the upstream repository
/// Optionally enable automatic sync from the upstream repository
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostByOrgReposRequestUpstreamAutosync {
    PostByOrgReposRequestUpstreamAutosyncOneOf(models::PostByOrgReposRequestUpstreamAutosyncOneOf),
}

impl Default for PostByOrgReposRequestUpstreamAutosync {
    fn default() -> Self {
        Self::PostByOrgReposRequestUpstreamAutosyncOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "poll")]
    Poll,
}

impl Default for Type {
    fn default() -> Type {
        Self::Poll
    }
}
/// Conflict resolution strategy. \"none\" means sync will fail on conflicts.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResolutionStrategy {
    #[serde(rename = "none")]
    None,
}

impl Default for ResolutionStrategy {
    fn default() -> ResolutionStrategy {
        Self::None
    }
}

