/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgReposRequestUpstream {
    /// URL of the upstream repository
    #[serde(rename = "uri")]
    pub uri: String,
    #[serde(rename = "autosync", skip_serializing_if = "Option::is_none")]
    pub autosync: Option<models::PostByOrgReposRequestUpstreamAutosync>,
    #[serde(rename = "token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub token: Option<Option<String>>,
    /// Username for git credential auth. Defaults to \"x-access-token\". Use actual username for Bitbucket app passwords.
    #[serde(rename = "token_username", skip_serializing_if = "Option::is_none")]
    pub token_username: Option<String>,
}

impl PostByOrgReposRequestUpstream {
    pub fn new(uri: String) -> PostByOrgReposRequestUpstream {
        PostByOrgReposRequestUpstream {
            uri,
            autosync: None,
            token: None,
            token_username: None,
        }
    }
}

