/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoWebhooksRequest {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<Events>>,
    #[serde(rename = "branches", skip_serializing_if = "Option::is_none")]
    pub branches: Option<Vec<String>>,
    #[serde(rename = "globs", skip_serializing_if = "Option::is_none")]
    pub globs: Option<Vec<String>>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl PostByOrgByRepoWebhooksRequest {
    pub fn new(url: String) -> PostByOrgByRepoWebhooksRequest {
        PostByOrgByRepoWebhooksRequest {
            url,
            events: None,
            branches: None,
            globs: None,
            secret: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Events {
    #[serde(rename = "push")]
    Push,
}

impl Default for Events {
    fn default() -> Events {
        Self::Push
    }
}

