/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgApiKeysRequest {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<Scopes>>,
}

impl PostByOrgApiKeysRequest {
    pub fn new() -> PostByOrgApiKeysRequest {
        PostByOrgApiKeysRequest {
            name: None,
            scopes: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scopes {
    #[serde(rename = "git:read")]
    GitColonRead,
    #[serde(rename = "git:write")]
    GitColonWrite,
    #[serde(rename = "repo:read")]
    RepoColonRead,
    #[serde(rename = "repo:create")]
    RepoColonCreate,
    #[serde(rename = "repo:delete")]
    RepoColonDelete,
    #[serde(rename = "webhook:read")]
    WebhookColonRead,
    #[serde(rename = "webhook:write")]
    WebhookColonWrite,
    #[serde(rename = "admin")]
    Admin,
}

impl Default for Scopes {
    fn default() -> Scopes {
        Self::GitColonRead
    }
}

