/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostByOrgByRepoMergeByBaseRequestAuthor : The author of the merge commit
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoMergeByBaseRequestAuthor {
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date: Option<Option<String>>,
}

impl PostByOrgByRepoMergeByBaseRequestAuthor {
    /// The author of the merge commit
    pub fn new(name: Option<String>, email: String) -> PostByOrgByRepoMergeByBaseRequestAuthor {
        PostByOrgByRepoMergeByBaseRequestAuthor {
            name,
            email,
            date: None,
        }
    }
}

