/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoBranchesRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "from")]
    pub from: String,
}

impl PostByOrgByRepoBranchesRequest {
    pub fn new(name: String, from: String) -> PostByOrgByRepoBranchesRequest {
        PostByOrgByRepoBranchesRequest {
            name,
            from,
        }
    }
}

