/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoMergeByBase200Response {
    /// The type of merge that was performed
    #[serde(rename = "merge_type")]
    pub merge_type: MergeType,
    /// The SHA of the resulting commit on the base branch
    #[serde(rename = "sha")]
    pub sha: String,
    /// The base branch that was merged into
    #[serde(rename = "base")]
    pub base: String,
    /// The head branch that was merged from
    #[serde(rename = "head")]
    pub head: String,
    /// Whether the head branch was deleted after merge
    #[serde(rename = "branch_deleted")]
    pub branch_deleted: bool,
}

impl PostByOrgByRepoMergeByBase200Response {
    pub fn new(merge_type: MergeType, sha: String, base: String, head: String, branch_deleted: bool) -> PostByOrgByRepoMergeByBase200Response {
        PostByOrgByRepoMergeByBase200Response {
            merge_type,
            sha,
            base,
            head,
            branch_deleted,
        }
    }
}
/// The type of merge that was performed
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MergeType {
    #[serde(rename = "fast_forward")]
    FastForward,
    #[serde(rename = "merge_commit")]
    MergeCommit,
}

impl Default for MergeType {
    fn default() -> MergeType {
        Self::FastForward
    }
}

