/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoLfsObjects200Response {
    #[serde(rename = "objects")]
    pub objects: Vec<models::PostByOrgByRepoLfsObjects200ResponseObjectsInner>,
}

impl PostByOrgByRepoLfsObjects200Response {
    pub fn new(objects: Vec<models::PostByOrgByRepoLfsObjects200ResponseObjectsInner>) -> PostByOrgByRepoLfsObjects200Response {
        PostByOrgByRepoLfsObjects200Response {
            objects,
        }
    }
}

