/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoCommitsRequestFilesInnerAnyOf2Lfs {
    #[serde(rename = "oid")]
    pub oid: String,
    #[serde(rename = "size")]
    pub size: i64,
}

impl PostByOrgByRepoCommitsRequestFilesInnerAnyOf2Lfs {
    pub fn new(oid: String, size: i64) -> PostByOrgByRepoCommitsRequestFilesInnerAnyOf2Lfs {
        PostByOrgByRepoCommitsRequestFilesInnerAnyOf2Lfs {
            oid,
            size,
        }
    }
}

