/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoCommits201Response {
    #[serde(rename = "sha", deserialize_with = "Option::deserialize")]
    pub sha: Option<String>,
    #[serde(rename = "branch", deserialize_with = "Option::deserialize")]
    pub branch: Option<String>,
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<String>,
}

impl PostByOrgByRepoCommits201Response {
    pub fn new(sha: Option<String>, branch: Option<String>, message: Option<String>) -> PostByOrgByRepoCommits201Response {
        PostByOrgByRepoCommits201Response {
            sha,
            branch,
            message,
        }
    }
}

