/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoBranches201Response {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "head_sha")]
    pub head_sha: String,
    #[serde(rename = "is_default")]
    pub is_default: bool,
}

impl PostByOrgByRepoBranches201Response {
    pub fn new(name: String, head_sha: String, is_default: bool) -> PostByOrgByRepoBranches201Response {
        PostByOrgByRepoBranches201Response {
            name,
            head_sha,
            is_default,
        }
    }
}

