/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoWebhooks201Response {
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    #[serde(rename = "url", deserialize_with = "Option::deserialize")]
    pub url: Option<String>,
    #[serde(rename = "events")]
    pub events: Vec<Events>,
    #[serde(rename = "branches", deserialize_with = "Option::deserialize")]
    pub branches: Option<Vec<String>>,
    #[serde(rename = "globs", deserialize_with = "Option::deserialize")]
    pub globs: Option<Vec<String>>,
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", deserialize_with = "Option::deserialize")]
    pub updated_at: Option<String>,
    #[serde(rename = "secret", deserialize_with = "Option::deserialize")]
    pub secret: Option<String>,
}

impl PostByOrgByRepoWebhooks201Response {
    pub fn new(id: Option<String>, url: Option<String>, events: Vec<Events>, branches: Option<Vec<String>>, globs: Option<Vec<String>>, created_at: Option<String>, updated_at: Option<String>, secret: Option<String>) -> PostByOrgByRepoWebhooks201Response {
        PostByOrgByRepoWebhooks201Response {
            id,
            url,
            events,
            branches,
            globs,
            created_at,
            updated_at,
            secret,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Events {
    #[serde(rename = "push")]
    Push,
}

impl Default for Events {
    fn default() -> Events {
        Self::Push
    }
}

