/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgReposRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "default_branch", skip_serializing_if = "Option::is_none")]
    pub default_branch: Option<String>,
    #[serde(rename = "upstream", skip_serializing_if = "Option::is_none")]
    pub upstream: Option<models::PostByOrgReposRequestUpstream>,
}

impl PostByOrgReposRequest {
    pub fn new(name: String) -> PostByOrgReposRequest {
        PostByOrgReposRequest {
            name,
            default_branch: None,
            upstream: None,
        }
    }
}

