/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoCommitsRequestFilesInnerAnyOf1 {
    #[serde(rename = "path", deserialize_with = "Option::deserialize")]
    pub path: Option<String>,
    #[serde(rename = "action")]
    pub action: Action,
}

impl PostByOrgByRepoCommitsRequestFilesInnerAnyOf1 {
    pub fn new(path: Option<String>, action: Action) -> PostByOrgByRepoCommitsRequestFilesInnerAnyOf1 {
        PostByOrgByRepoCommitsRequestFilesInnerAnyOf1 {
            path,
            action,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "delete")]
    Delete,
}

impl Default for Action {
    fn default() -> Action {
        Self::Delete
    }
}

