/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoCommitsRequest {
    #[serde(rename = "branch")]
    pub branch: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "author")]
    pub author: models::GetByOrgByRepoCommits200ResponseCommitsInnerCommitter,
    #[serde(rename = "base_sha", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub base_sha: Option<Option<String>>,
    #[serde(rename = "files")]
    pub files: Vec<models::PostByOrgByRepoCommitsRequestFilesInner>,
}

impl PostByOrgByRepoCommitsRequest {
    pub fn new(branch: String, message: String, author: models::GetByOrgByRepoCommits200ResponseCommitsInnerCommitter, files: Vec<models::PostByOrgByRepoCommitsRequestFilesInner>) -> PostByOrgByRepoCommitsRequest {
        PostByOrgByRepoCommitsRequest {
            branch,
            message,
            author,
            base_sha: None,
            files,
        }
    }
}

