/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoLfsObjects200ResponseObjectsInner {
    #[serde(rename = "oid", deserialize_with = "Option::deserialize")]
    pub oid: Option<String>,
    #[serde(rename = "size")]
    pub size: f64,
    #[serde(rename = "upload_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upload_url: Option<Option<String>>,
    #[serde(rename = "download_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub download_url: Option<Option<String>>,
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<f64>,
    #[serde(rename = "exists")]
    pub exists: bool,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<models::PostByOrgByRepoLfsObjects200ResponseObjectsInnerError>,
}

impl PostByOrgByRepoLfsObjects200ResponseObjectsInner {
    pub fn new(oid: Option<String>, size: f64, exists: bool) -> PostByOrgByRepoLfsObjects200ResponseObjectsInner {
        PostByOrgByRepoLfsObjects200ResponseObjectsInner {
            oid,
            size,
            upload_url: None,
            download_url: None,
            expires_in: None,
            exists,
            error: None,
        }
    }
}

