/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgApiKeys201Response {
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<String>,
    #[serde(rename = "key", deserialize_with = "Option::deserialize")]
    pub key: Option<String>,
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "created_at", deserialize_with = "Option::deserialize")]
    pub created_at: Option<String>,
}

impl PostByOrgApiKeys201Response {
    pub fn new(id: Option<String>, key: Option<String>, name: Option<String>, scopes: Vec<String>, created_at: Option<String>) -> PostByOrgApiKeys201Response {
        PostByOrgApiKeys201Response {
            id,
            key,
            name,
            scopes,
            created_at,
        }
    }
}

