/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoBranchesRequest {
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<String>,
    #[serde(rename = "from", deserialize_with = "Option::deserialize")]
    pub from: Option<String>,
}

impl PostByOrgByRepoBranchesRequest {
    pub fn new(name: Option<String>, from: Option<String>) -> PostByOrgByRepoBranchesRequest {
        PostByOrgByRepoBranchesRequest {
            name,
            from,
        }
    }
}

