/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoCommitsRequestFilesInner {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "encoding", skip_serializing_if = "Option::is_none")]
    pub encoding: Option<Encoding>,
    #[serde(rename = "action")]
    pub action: Action,
    #[serde(rename = "lfs")]
    pub lfs: models::PostByOrgByRepoCommitsRequestFilesInnerAnyOf2Lfs,
}

impl PostByOrgByRepoCommitsRequestFilesInner {
    pub fn new(path: String, content: String, action: Action, lfs: models::PostByOrgByRepoCommitsRequestFilesInnerAnyOf2Lfs) -> PostByOrgByRepoCommitsRequestFilesInner {
        PostByOrgByRepoCommitsRequestFilesInner {
            path,
            content,
            encoding: None,
            action,
            lfs,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Encoding {
    #[serde(rename = "utf-8")]
    Utf8,
    #[serde(rename = "base64")]
    Base64,
}

impl Default for Encoding {
    fn default() -> Encoding {
        Self::Utf8
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "delete")]
    Delete,
}

impl Default for Action {
    fn default() -> Action {
        Self::Delete
    }
}

