/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoMergeByBaseRequest {
    /// The branch to merge from
    #[serde(rename = "head")]
    pub head: String,
    /// Custom merge commit message. Defaults to \"Merge branch 'head' into 'base'\"
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "author")]
    pub author: models::PostByOrgByRepoMergeByBaseRequestAuthor,
    /// Whether to delete the head branch after a successful merge
    #[serde(rename = "delete_branch", skip_serializing_if = "Option::is_none")]
    pub delete_branch: Option<bool>,
}

impl PostByOrgByRepoMergeByBaseRequest {
    pub fn new(head: String, author: models::PostByOrgByRepoMergeByBaseRequestAuthor) -> PostByOrgByRepoMergeByBaseRequest {
        PostByOrgByRepoMergeByBaseRequest {
            head,
            message: None,
            author,
            delete_branch: None,
        }
    }
}

