/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostByOrgByRepoLfsObjects200ResponseObjectsInnerError {
    #[serde(rename = "code", deserialize_with = "Option::deserialize")]
    pub code: Option<String>,
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<String>,
}

impl PostByOrgByRepoLfsObjects200ResponseObjectsInnerError {
    pub fn new(code: Option<String>, message: Option<String>) -> PostByOrgByRepoLfsObjects200ResponseObjectsInnerError {
        PostByOrgByRepoLfsObjects200ResponseObjectsInnerError {
            code,
            message,
        }
    }
}

