/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_by_org_by_repo_content`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetByOrgByRepoContentError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}


/// Get file content or directory listing at a path. Use Accept: application/json for the JSON union response, or Accept: application/octet-stream for raw file bytes. Directory + octet-stream requests return 406 Not Acceptable.
pub async fn get_by_org_by_repo_content(configuration: &configuration::Configuration, org: &str, repo: &str, r#ref: Option<&str>, path: Option<&str>, depth: Option<u64>) -> Result<models::GetByOrgByRepoContent200Response, Error<GetByOrgByRepoContentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_org = org;
    let p_repo = repo;
    let p_ref = r#ref;
    let p_path = path;
    let p_depth = depth;

    let uri_str = format!("{}/{org}/{repo}/content", configuration.base_path, org=crate::apis::urlencode(p_org), repo=crate::apis::urlencode(p_repo));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_ref {
        req_builder = req_builder.query(&[("ref", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_path {
        req_builder = req_builder.query(&[("path", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_depth {
        req_builder = req_builder.query(&[("depth", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetByOrgByRepoContent200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetByOrgByRepoContent200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetByOrgByRepoContentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

