/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_by_org_by_repo_diff`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetByOrgByRepoDiffError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}


/// Retrieve the diff between two refs
pub async fn get_by_org_by_repo_diff(configuration: &configuration::Configuration, org: &str, repo: &str, base: &str, head: &str) -> Result<models::GetByOrgByRepoDiff200Response, Error<GetByOrgByRepoDiffError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org = org;
    let p_path_repo = repo;
    let p_query_base = base;
    let p_query_head = head;

    let uri_str = format!("{}/{org}/{repo}/diff", configuration.base_path, org=crate::apis::urlencode(p_path_org), repo=crate::apis::urlencode(p_path_repo));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("base", &p_query_base.to_string())]);
    req_builder = req_builder.query(&[("head", &p_query_head.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetByOrgByRepoDiff200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetByOrgByRepoDiff200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetByOrgByRepoDiffError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

