/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`post_by_org_by_repo_lfs_objects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostByOrgByRepoLfsObjectsError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_by_org_by_repo_lfs_objects_download`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostByOrgByRepoLfsObjectsDownloadError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}


/// Request pre-signed URLs to upload large files to LFS storage. After uploading, use the commit endpoint with LFS file references to create commits.
pub async fn post_by_org_by_repo_lfs_objects(configuration: &configuration::Configuration, org: &str, repo: &str, post_by_org_by_repo_lfs_objects_request: Option<models::PostByOrgByRepoLfsObjectsRequest>) -> Result<models::PostByOrgByRepoLfsObjects200Response, Error<PostByOrgByRepoLfsObjectsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_org = org;
    let p_repo = repo;
    let p_post_by_org_by_repo_lfs_objects_request = post_by_org_by_repo_lfs_objects_request;

    let uri_str = format!("{}/{org}/{repo}/lfs/objects", configuration.base_path, org=crate::apis::urlencode(p_org), repo=crate::apis::urlencode(p_repo));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_post_by_org_by_repo_lfs_objects_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostByOrgByRepoLfsObjects200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostByOrgByRepoLfsObjects200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostByOrgByRepoLfsObjectsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Request pre-signed URLs to download large files from LFS storage.
pub async fn post_by_org_by_repo_lfs_objects_download(configuration: &configuration::Configuration, org: &str, repo: &str, post_by_org_by_repo_lfs_objects_request: Option<models::PostByOrgByRepoLfsObjectsRequest>) -> Result<models::PostByOrgByRepoLfsObjects200Response, Error<PostByOrgByRepoLfsObjectsDownloadError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_org = org;
    let p_repo = repo;
    let p_post_by_org_by_repo_lfs_objects_request = post_by_org_by_repo_lfs_objects_request;

    let uri_str = format!("{}/{org}/{repo}/lfs/objects/download", configuration.base_path, org=crate::apis::urlencode(p_org), repo=crate::apis::urlencode(p_repo));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_post_by_org_by_repo_lfs_objects_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostByOrgByRepoLfsObjects200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostByOrgByRepoLfsObjects200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostByOrgByRepoLfsObjectsDownloadError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

