/*
 * Depot API
 *
 * Depot HTTP API v1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`delete_by_org_by_repo`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteByOrgByRepoError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_by_org_by_repo`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetByOrgByRepoError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_by_org_by_repo_sync`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetByOrgByRepoSyncError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_by_org_repos`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetByOrgReposError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_by_org_by_repo`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchByOrgByRepoError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_by_org_by_repo_sync`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostByOrgByRepoSyncError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_by_org_repos`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostByOrgReposError {
    Status400(models::PostByOrgApiKeys400Response),
    Status401(models::PostByOrgApiKeys400Response),
    Status403(models::PostByOrgApiKeys400Response),
    Status404(models::PostByOrgApiKeys400Response),
    Status406(models::PostByOrgApiKeys400Response),
    Status409(models::PostByOrgApiKeys400Response),
    Status500(models::PostByOrgApiKeys400Response),
    UnknownValue(serde_json::Value),
}


/// Permanently delete a repository and all its data
pub async fn delete_by_org_by_repo(configuration: &configuration::Configuration, org: &str, repo: &str) -> Result<models::DeleteByOrgApiKeysById200Response, Error<DeleteByOrgByRepoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org = org;
    let p_path_repo = repo;

    let uri_str = format!("{}/{org}/{repo}", configuration.base_path, org=crate::apis::urlencode(p_path_org), repo=crate::apis::urlencode(p_path_repo));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteByOrgApiKeysById200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteByOrgApiKeysById200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteByOrgByRepoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get metadata for a specific repository
pub async fn get_by_org_by_repo(configuration: &configuration::Configuration, org: &str, repo: Option<&str>) -> Result<models::PostByOrgRepos201Response, Error<GetByOrgByRepoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org = org;
    let p_path_repo = repo;

    let uri_str = format!("{}/{org}/{repo}", configuration.base_path, org=crate::apis::urlencode(p_path_org), repo=crate::apis::urlencode(p_path_repo.unwrap()));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostByOrgRepos201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostByOrgRepos201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetByOrgByRepoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the sync status for a repository with upstream configured
pub async fn get_by_org_by_repo_sync(configuration: &configuration::Configuration, org: &str, repo: &str) -> Result<models::GetByOrgByRepoSync200Response, Error<GetByOrgByRepoSyncError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org = org;
    let p_path_repo = repo;

    let uri_str = format!("{}/{org}/{repo}/sync", configuration.base_path, org=crate::apis::urlencode(p_path_org), repo=crate::apis::urlencode(p_path_repo));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetByOrgByRepoSync200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetByOrgByRepoSync200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetByOrgByRepoSyncError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List all repositories in the organization
pub async fn get_by_org_repos(configuration: &configuration::Configuration, org: Option<&str>, cursor: Option<&str>, limit: Option<u8>) -> Result<models::GetByOrgRepos200Response, Error<GetByOrgReposError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org = org;
    let p_query_cursor = cursor;
    let p_query_limit = limit;

    let uri_str = format!("{}/{org}/repos", configuration.base_path, org=crate::apis::urlencode(p_path_org.unwrap()));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetByOrgRepos200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetByOrgRepos200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetByOrgReposError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update repository name or upstream configuration
pub async fn patch_by_org_by_repo(configuration: &configuration::Configuration, org: &str, repo: &str, patch_by_org_by_repo_request: Option<models::PatchByOrgByRepoRequest>) -> Result<models::PostByOrgRepos201Response, Error<PatchByOrgByRepoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org = org;
    let p_path_repo = repo;
    let p_body_patch_by_org_by_repo_request = patch_by_org_by_repo_request;

    let uri_str = format!("{}/{org}/{repo}", configuration.base_path, org=crate::apis::urlencode(p_path_org), repo=crate::apis::urlencode(p_path_repo));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_patch_by_org_by_repo_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostByOrgRepos201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostByOrgRepos201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchByOrgByRepoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Trigger a sync from the upstream repository. Waits for sync to complete.
pub async fn post_by_org_by_repo_sync(configuration: &configuration::Configuration, org: &str, repo: &str) -> Result<models::DeleteByOrgApiKeysById200Response, Error<PostByOrgByRepoSyncError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org = org;
    let p_path_repo = repo;

    let uri_str = format!("{}/{org}/{repo}/sync", configuration.base_path, org=crate::apis::urlencode(p_path_org), repo=crate::apis::urlencode(p_path_repo));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteByOrgApiKeysById200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteByOrgApiKeysById200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostByOrgByRepoSyncError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a new repository in the organization
pub async fn post_by_org_repos(configuration: &configuration::Configuration, org: &str, post_by_org_repos_request: Option<models::PostByOrgReposRequest>) -> Result<models::PostByOrgRepos201Response, Error<PostByOrgReposError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_org = org;
    let p_body_post_by_org_repos_request = post_by_org_repos_request;

    let uri_str = format!("{}/{org}/repos", configuration.base_path, org=crate::apis::urlencode(p_path_org));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_post_by_org_repos_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_path_to_error::deserialize(&mut serde_json::Deserializer::from_str(&content)).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PostByOrgRepos201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PostByOrgRepos201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostByOrgReposError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

