FROM alpine:latest

RUN apk add --no-cache curl gcc musl-dev
RUN apk add --no-cache dasel
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --component clippy --component rustfmt

ENV PATH="/root/.cargo/bin:${PATH}"
